"""Event system for decoupled progress reporting (console, JSON, future GUI)."""

from argus.events.bus import EventBus
from argus.events.events import (
    ActionCompleted,
    ActionStarted,
    Event,
    FeatureSetupCompleted,
    FeatureSetupStarted,
    FeatureTeardownCompleted,
    FeatureTeardownStarted,
    PreflightCheckCompleted,
    PreflightCompleted,
    PreflightStarted,
    SuiteSetupCompleted,
    SuiteSetupStarted,
    SuiteTeardownCompleted,
    SuiteTeardownStarted,
    TestFailed,
    TestPassed,
    TestRunCompleted,
    TestRunStarted,
    TestSkipped,
    TestStarted,
    VerificationCompleted,
    VerificationStarted,
)

__all__ = [
    "ActionCompleted",
    "ActionStarted",
    "Event",
    "FeatureSetupCompleted",
    "FeatureSetupStarted",
    "FeatureTeardownCompleted",
    "FeatureTeardownStarted",
    "EventBus",
    "PreflightCheckCompleted",
    "PreflightCompleted",
    "PreflightStarted",
    "SuiteSetupCompleted",
    "SuiteSetupStarted",
    "SuiteTeardownCompleted",
    "SuiteTeardownStarted",
    "TestFailed",
    "TestPassed",
    "TestRunCompleted",
    "TestRunStarted",
    "TestSkipped",
    "TestStarted",
    "VerificationCompleted",
    "VerificationStarted",
]
